# Generated by Django 4.0.4 on 2022-06-02 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_name', models.CharField(max_length=30)),
                ('writer_photo', models.ImageField(upload_to='writer-name')),
                ('book_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Writer_app.booklist')),
            ],
        ),
    ]
